# Generated by Django 5.1.6 on 2025-03-13 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('document_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='文档号')),
                ('date', models.DateField(blank=True, null=True, verbose_name='日期')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_special', models.BooleanField(default=False, verbose_name='是否特殊项目')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '档案盒',
                'verbose_name_plural': '档案盒',
            },
        ),
        migrations.CreateModel(
            name='ArchiveRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='档案室名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '档案室',
                'verbose_name_plural': '档案室',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('information', models.TextField(blank=True, null=True, verbose_name='基本信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['-year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('import_date', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('copy_count', models.PositiveIntegerField(default=1, verbose_name='份数')),
                ('is_in_stock', models.BooleanField(default=True, verbose_name='是否在库中')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='archives.archivebox', verbose_name='所属档案盒')),
            ],
            options={
                'verbose_name': '档案',
                'verbose_name_plural': '档案',
            },
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet_number', models.CharField(max_length=50, verbose_name='柜子编号')),
                ('rows', models.PositiveIntegerField(default=5, verbose_name='行数')),
                ('columns', models.PositiveIntegerField(default=5, verbose_name='列数')),
                ('archive_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinets', to='archives.archiveroom', verbose_name='所属档案室')),
            ],
            options={
                'verbose_name': '柜子',
                'verbose_name_plural': '柜子',
            },
        ),
        migrations.AddField(
            model_name='archivebox',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_boxes', to='archives.project', verbose_name='所属项目'),
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('left', '左侧'), ('right', '右侧')], max_length=5, verbose_name='侧面')),
                ('row', models.PositiveIntegerField(verbose_name='行号')),
                ('column', models.PositiveIntegerField(verbose_name='列号')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='是否已占用')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='archives.cabinet', verbose_name='所属柜子')),
            ],
            options={
                'verbose_name': '格子',
                'verbose_name_plural': '格子',
                'unique_together': {('cabinet', 'side', 'row', 'column')},
            },
        ),
        migrations.AddField(
            model_name='archivebox',
            name='slot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_box', to='archives.slot', verbose_name='所在格子'),
        ),
    ]
