# Generated by Django 5.1.6 on 2025-03-03 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='档案室名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '档案室',
                'verbose_name_plural': '档案室',
            },
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet_number', models.CharField(max_length=50, verbose_name='柜子编号')),
                ('rows', models.PositiveIntegerField(default=5, verbose_name='行数')),
                ('columns', models.PositiveIntegerField(default=5, verbose_name='列数')),
                ('archive_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinets', to='archives.archiveroom', verbose_name='所属档案室')),
            ],
            options={
                'verbose_name': '柜子',
                'verbose_name_plural': '柜子',
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('left', '左侧'), ('right', '右侧')], max_length=5, verbose_name='侧面')),
                ('row', models.PositiveIntegerField(verbose_name='行号')),
                ('column', models.PositiveIntegerField(verbose_name='列号')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='是否已占用')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='archives.cabinet', verbose_name='所属柜子')),
            ],
            options={
                'verbose_name': '格子',
                'verbose_name_plural': '格子',
                'unique_together': {('cabinet', 'side', 'row', 'column')},
            },
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='档案编号')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('slot', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive', to='archives.slot', verbose_name='存放位置')),
            ],
            options={
                'verbose_name': '档案',
                'verbose_name_plural': '档案',
            },
        ),
    ]
