# Generated by Django 5.1.6 on 2025-03-03 06:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='code',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='archive',
            name='copy_count',
            field=models.PositiveIntegerField(default=1, verbose_name='份数'),
        ),
        migrations.AddField(
            model_name='archive',
            name='import_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='入库时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archive',
            name='is_in_stock',
            field=models.BooleanField(default=True, verbose_name='是否在库中'),
        ),
    ]
