# Generated by Django 5.1.6 on 2025-03-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='项目简称'),
        ),
    ]
