# Generated by Django 5.1.6 on 2025-03-03 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_remove_archive_code_remove_archive_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_number', models.CharField(max_length=50, verbose_name='档案盒编号')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '档案盒',
                'verbose_name_plural': '档案盒',
            },
        ),
        migrations.AddField(
            model_name='archive',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='是否特殊档案'),
        ),
        migrations.AddField(
            model_name='archive',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archives', to='archives.archivebox', verbose_name='所属档案盒'),
        ),
    ]
