# Generated by Django 5.1.6 on 2025-03-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_project_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='archives/pdfs/%Y/%m/', verbose_name='PDF扫描件'),
        ),
    ]
