# Generated by Django 5.1.6 on 2025-04-22 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_archive_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivebox',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_boxes', to='archives.slot', verbose_name='所在格子'),
        ),
    ]
