# Generated by Django 5.1.6 on 2025-03-03 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_archivebox_archive_is_special_archive_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='is_special',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='slot',
        ),
        migrations.AddField(
            model_name='archivebox',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='是否特殊项目'),
        ),
        migrations.AddField(
            model_name='archivebox',
            name='slot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_box', to='archives.slot', verbose_name='所在格子'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='box',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='archives.archivebox', verbose_name='所属档案盒'),
            preserve_default=False,
        ),
    ]
