# Generated by Django 5.1.6 on 2025-03-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0004_remove_archive_is_special_remove_archive_slot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivebox',
            name='box_number',
        ),
        migrations.AddField(
            model_name='archivebox',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='日期'),
        ),
        migrations.AddField(
            model_name='archivebox',
            name='document_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='文档号'),
        ),
        migrations.AddField(
            model_name='archivebox',
            name='name',
            field=models.CharField(default='未命名档案盒', max_length=100, verbose_name='名称'),
            preserve_default=False,
        ),
    ]
