# Generated by Django 5.1.3 on 2025-03-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0005_remove_archivebox_box_number_archivebox_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='import_date',
            field=models.DateTimeField(verbose_name='入库时间'),
        ),
    ]
